import Products from "@/components/Home/Products/Products";
import React from "react";

export const metadata = {
  title: "All Toys",
  description: "Generated by create next app",
};

const AllProducts = () => {
  return (
    <div>
      <Products></Products>
    </div>
  );
};

export default AllProducts;
